# Generated by Django 4.2 on 2023-04-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_users_user_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
