# Generated by Django 4.2 on 2023-05-02 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_users_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='user',
        ),
    ]
